### ISSUE TITLE
GH k32 c30 plots don't work

### ISSUE THREAD

**Issue by Jsewill** [evergreen-xch/ff_giga_bins#3]
When attempting to farm any GH k32 c30 plot with Fast Farmer, the following error is produced:

```shell
2024-04-21T03:45:06.852Z ERROR [ff_giga::harvesters::gigahorse] Failed to open plot: Custom { kind: NotFound, error: "Error When loading Plot: <redacted>, badbit or failbit after reading size 4 at position <redacted>" }
```

May be similar to issue #2

**Comment by DaOneLuna** [comment]
Can you try with 1.0.4 and see if you are still having issues? I dont think there is any reason c30 shouldnt work.

**Comment by Jsewill** [comment]
Now it outputs the following for what appears to be every plot:

```shell
2024-04-24T20:25:32.709Z ERROR [ff_giga::harvesters::gigahorse] Failed to read plot at path "<redacted>", got error Custom { kind: InvalidData, error: "Invalid SubSlot Iterations: 7472444697301231282" }
```

even though, all the paths are readable.

**Comment by bobwya** [comment]
I'm seeing this issue as well when trying to farm with **ff_giga 1.0.4** using **Gigahorse k32 C19** plots.
This error appears for every plot (with same subslot iterations number):

`ERROR [ff_giga::harvesters::gigahorse] Failed to read plot at path "<redacted>.plot", got error Custom { kind: InvalidData, error: "Invalid SubSlot Iterations: 2637237091261971793" }
`

[nvidia_smi.txt](https://github.com/evergreen-xch/ff_giga_bins/files/15137870/nvidia_smi.txt)

**Comment by Jsewill** [comment]
Is there anything more I can do to help track down this problem?

**Comment by Jsewill** [comment]
Still having this issue. I would like to use fastfarmer, if possible.

It spits out about 500 of these errors every few seconds, and doesn't recognize any of my plots as valid.

```shell
ERROR [ff_giga::harvesters::gigahorse] Failed to read plot at path "<redacted>.plot", got error Custom { kind: InvalidData, error: "Invalid SubSlot Iterations: 3825584859349943299" }
```

**Comment by Jsewill** [comment]
After learning that others were able to get this to work using the foxypool community node, I gave it a go. It works. That might indicate that ff_giga isn't properly picking up or using the certs.

**Comment by Jsewill** [comment]
It appears it is simply incompatible with the chia-gigahorse full node. The regular chia full node plays nice with fastfarmer.
